### ISSUE TITLE
Use the FLTK or GTK+ theme rather than Gleam theme by default

### ISSUE THREAD

**Issue by fpesari** [Stazed/rakarrack-plus#21]
Hello,

Gleam looks very bad on my PC, very 1990s with gradients which aren't almost never used in GUIs:

![image](https://user-images.githubusercontent.com/52702101/107124188-96449600-68a2-11eb-9894-e70b93e975b0.png)

FLTK looks a lot better, but has some white borders which look weird, and old-style comboboxes:

![image](https://user-images.githubusercontent.com/52702101/107124224-cb50e880-68a2-11eb-8bae-24112b58582c.png)

GTK+ IMHO looks the best, even if those blue controls need to be replaced:

![image](https://user-images.githubusercontent.com/52702101/107124248-f63b3c80-68a2-11eb-89ad-a05fcaa1f60c.png)

FLTK are GTK+ are both better than Gleam IMHO, even if they need some fixes. I am no graphic designer but if you allow me, I can make some mockups for an user-friendlier interface, with the feedback of some people who use the rakarrack-plus package I made on openSUSE.

Meanwhile, I kindly ask to switch away from Gleam, since it looks very dated and doesn't help people get that this is a modern fork of rakarrack. These are my 2 cents, not as a designer but as a packager and user. Thank you for listening :smile_cat:

**Comment by fpesari** [comment]
I would also remove that big red "Rakarrack+", shrink it and move it to the top right. Here is a mockup using the Hemi Head 426 font. (of course, in actual code it would look a bit different, since a lot of blank space would disappear).

![107124248-f63b3c80-68a2-11eb-89ad-a05fcaa1f60c](https://user-images.githubusercontent.com/52702101/107125015-72378380-68a7-11eb-973e-9788ce67c1ce.png)

**Comment by Stazed** [comment]
I appears that you have replaced the default background .png in Settings/Look - Background Image with a bad .png.
This shows up for Gleam as the gradients, but not for the other themes. Try running the program in a terminal and check for an error:
libpng error: Read Error
PNG file or data "/home/user/testRKRstuff/badback.png" is too large or contains errors!

This is a known issue, due to the user selecting a bad/invalid .png. Unfortunately, when I looked at this over year ago, I could not find any way of capturing the FLTK error message and resetting the .png back to default. I will look at this again since it is likely to come up again. Perhaps some FLTK expert can point me in the right direction on how to capture the error.

To fix this you must set the Background Image to something valid, default is something like:
/usr/local/share/rakarrack-plus/blackbg.png. Obviously, the location may be different on your computer.
You will need to do this even if the button for "Enable Background Image" is unchecked.

**Comment by Stazed** [comment]
Regarding the big red "Rakarrack +", this is a button. Hover the mouse over the label for the tooltip. To see the Analyzer at work, you need to run some audio through the program with the main FX button ON. Otherwise it just looks like a blank space. Currently the color cannot be changed do to some issues in the way that color changes are updated. This will be fixed in the future, but is currently low priority.

**Comment by fpesari** [comment]
What about disabling themes and manually tweaking r+'s design to look the best using a single theme? Then maybe themes could be reintroduced if r+ ever gets a full-time designer. I think custom themes can be a great feature if there's someone working on every theme to make sure it looks great, else they become a burden and I would rather have a theme which consistently looks decent for all users.

**Comment by Stazed** [comment]
> I would rather have a theme which consistently looks decent for all users.

This is virtually impossible. Different monitors, different taste, different visual acuity...
Honestly, the theme and look are low priority. I don't want to even think about this any more. It provides no functional benefit and is a waste of my time right now. I'm closing this. Ask me again in a year if this project is still going.
